---
title: 'Rapport Prédiction'
author: "KOAN Kenjy"
date: "3/18/2021"
output:
  pdf_document: default
---

# Prédiction de fréquentation des cyclistes à Montpellier

## Introduction 

 Il est nécessaire de commencer par étudier la distribution des données. 

On observe ici qu’il y a un socle de base de 0 à 2000 cyclistes par jour toute l’année. De plus, on repère 2 pics pour lesquels on soumet l’hypothèse de l’augmentation des températures et l’arrivé d’une météo plus clémente. Cependant il y a un gap entre ces deux pics qui arrive au moment de la période des vacances scolaires (commence début juillet et termine fin aout). 
Ces deux hypothèses mettent en avant le principe de saisonnalité, c’est-à-dire que si elles s’avèrent être vrai ce phénomène se répètera d’année en année.
D’un point de vue plus microscopique, une répétition est identifiable par semaine. Cependant cette répétition n’est pas stable (si l’hypothèse de la météo est vérifiée cette non-stabilité pourrait être expliqué) et ne permet pas d’identifier une saisonnalité précise. 


Les données :
Les données fournies sont celle de la fréquentation de cycliste dans Montpellier pour différent créneau horaire dans une journée sur un an (de mars 2020 à mars 2021).
